=== skrx7392/WPL-HW3/XMLSchema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Book">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="book" minOccurs="5" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="author">
								<xs:complexType>
									<xs:sequence>

										<xs:element name="authorname">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="lastname">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:pattern value="([A-Z]+[a-z]*)" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:choice minOccurs="0" maxOccurs="1">
														<xs:element name="MI">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:pattern value="([A-Z]+.)" />
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
													</xs:choice>
													<xs:element name="firstname">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:pattern value="([A-Z]+[a-z]*)" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="dateofbirth">
											<xs:simpleType>
												<xs:restriction base="xs:date">
													<xs:minInclusive value="1900-01-01">
													</xs:minInclusive>
													<xs:maxInclusive value="2015-12-31"></xs:maxInclusive>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="education">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="BA" />
													<xs:enumeration value="BS" />
													<xs:enumeration value="MS" />
													<xs:enumeration value="MBA" />
													<xs:enumeration value="PHD" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="address">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="street">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:pattern value="([0-9]+([ ][A-Z]+[a-z]*)+)"></xs:pattern>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:choice minOccurs="0" maxOccurs="1">
														<xs:element name="apt">
															<xs:simpleType>
																<xs:restriction base="xs:integer">
																	<xs:minExclusive value="100" />
																	<xs:maxInclusive value="2000" />
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
													</xs:choice>
													<xs:element name="city">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:pattern value="([A-Z][a-z]*)" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="zipcode">
														<xs:simpleType>
															<xs:restriction base="xs:integer">
																<xs:minInclusive value="11111" />
																<xs:maxInclusive value="99999" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="country">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:pattern value="([A-Z]+)" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:choice minOccurs="0" maxOccurs="unbounded">
											<xs:element name="Co-AuthorNames" type="xs:string">
											</xs:element>
										</xs:choice>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="PublisherInfo">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="PublisherName">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:pattern value="([A-Z]+[a-z]*)"></xs:pattern>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="PublisherAddress">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="StreetName">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:pattern value="([0-9]+([ ][A-Z]+[a-z]*)+)"></xs:pattern>

															</xs:restriction>
														</xs:simpleType>

													</xs:element>
													<xs:choice minOccurs="0" maxOccurs="1">
														<xs:element name="SuiteNumber" type="xs:integer">
														</xs:element>
													</xs:choice>
													<xs:element name="City">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:pattern value="([A-Z]+[a-z]*)"></xs:pattern>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="zipcode">
														<xs:simpleType>
															<xs:restriction base="xs:integer">
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="country">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:pattern value="([A-Z]+)" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>							
							<xs:element name="BookInfo">
								<xs:complexType>

									<xs:sequence>

										<xs:element name="Title">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:pattern value="([A-Z]+[a-z]*)([ ]?[A-Z]+[a-z]*)*"></xs:pattern>
												</xs:restriction>

											</xs:simpleType>
										</xs:element>
										<xs:element name="ISBN">

											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:pattern
														value="([0-9|A-Z|a-z]?[0-9|A-Z|a-z]?[0-9|A-Z|a-z]?(-)[0-9|A-Z|a-z]?[0-9|A-Z|a-z]?[0-9|A-Z|a-z]?(-)[0-9|A-Z|a-z]?[0-9|A-Z|a-z]?[0-9|A-Z|a-z]?[0-9|A-Z|a-z]?)">
													</xs:pattern>

												</xs:restriction>

											</xs:simpleType>
										</xs:element>

										<xs:element name="price">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:decimal">
														<xs:attribute name="currency" type="xs:string">
														</xs:attribute>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										
										<xs:element name="PublicationDate" type="xs:date">

										</xs:element>
										<xs:element name="TotalTime">
											<xs:simpleType>
												<xs:restriction base="xs:duration">
													<xs:pattern value="[\-]?P[0-9]+(Y([0-9]+M[0-9]?D)?|M)"></xs:pattern>
												</xs:restriction>
											</xs:simpleType>

										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>

	</xs:element>
	<xs:complexType name="AttrElement">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="currency" type="xs:string">
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== skrx7392/WPL-HW3/Books.xml
<?xml version="1.0" encoding="UTF-8"?>
<Book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchema.xsd">
  <book>
    <author>
      <authorname>
        <lastname>Brown</lastname>
        <firstname>Dan</firstname>
      </authorname>
      <dateofbirth>1994-06-22</dateofbirth>
      <education>MBA</education>
      <address>
        <street>100 Monalisa Dr</street>
        <apt>1100</apt>
        <city>Losangeles</city>
        <zipcode>56274</zipcode>
        <country>USA</country>
      </address>
    </author>
    <PublisherInfo>
      <PublisherName>Universities</PublisherName>
      <PublisherAddress>
        <StreetName>302 Dickerson Street</StreetName>
        <City>Pittsburgh</City>
        <zipcode>25746</zipcode>
        <country>USA</country>
      </PublisherAddress>
    </PublisherInfo>
    <BookInfo>
      <Title>Deception Point</Title>
      <ISBN>332-392-ISBN</ISBN>
      <price currency="Dollar">100.0</price>
      <PublicationDate>2003-03-18</PublicationDate>
      <TotalTime>P1Y7M5D</TotalTime>
    </BookInfo>
  </book>
   <book>
    <author>
      <authorname>
        <lastname>RK</lastname>
        <firstname>Narayan</firstname>
      </authorname>
      <dateofbirth>1977-08-24</dateofbirth>
      <education>BA</education>
      <address>
        <street>3456 West Rd</street>
        <apt>567</apt>
        <city>Hyderabad</city>
        <zipcode>50151</zipcode>
        <country>INDIA</country>
      </address>
    </author>
    <PublisherInfo>
      <PublisherName>Publications</PublisherName>
      <PublisherAddress>
        <StreetName>3756 Central Road</StreetName>
        <City>Bnglore</City>
        <zipcode>60024</zipcode>
        <country>INDIA</country>
      </PublisherAddress>
    </PublisherInfo>
    <BookInfo>
      <Title>Day To Remember</Title>
      <ISBN>123-455-6788</ISBN>
      <price currency="Dollar">50.0</price>
      <PublicationDate>2009-11-12</PublicationDate>
      <TotalTime>P2Y5M9D</TotalTime>
    </BookInfo>
  </book>
  <book>
    <author>
      <authorname>
        <lastname>Coelho</lastname>
        <firstname>Paulo</firstname>
      </authorname>
      <dateofbirth>1977-08-24</dateofbirth>
      <education>BS</education>
      <address>
        <street>456 Veronica Avenue</street>
        <apt>567</apt>
        <city>Rio</city>
        <zipcode>50151</zipcode>
        <country>BRAZIL</country>
      </address>
    </author>
    <PublisherInfo>
      <PublisherName>Harpertorch</PublisherName>
      <PublisherAddress>
        <StreetName>195 Broadway</StreetName>
        <City>Newyork</City>
        <zipcode>60024</zipcode>
        <country>USA</country>
      </PublisherAddress>
    </PublisherInfo>
    <BookInfo>
      <Title>The Alchemist</Title>
      <ISBN>123-455-6788</ISBN>
      <price currency="Dollar">35.0</price>
      <PublicationDate>2009-11-12</PublicationDate>
      <TotalTime>P2Y5M2D</TotalTime>
    </BookInfo>
  </book>
 <book>
    <author>
      <authorname>
        <lastname>Coelho</lastname>
        <firstname>Paulo</firstname>
      </authorname>
      <dateofbirth>1977-08-24</dateofbirth>
      <education>BS</education>
      <address>
        <street>456 Veronica Avenue</street>
        <apt>567</apt>
        <city>Rio</city>
        <zipcode>50151</zipcode>
        <country>BRAZIL</country>
      </address>
    </author>
    <PublisherInfo>
      <PublisherName>Harpertorch</PublisherName>
      <PublisherAddress>
        <StreetName>195 Broadway</StreetName>
        <City>Newyork</City>
        <zipcode>60024</zipcode>
        <country>USA</country>
      </PublisherAddress>
    </PublisherInfo>
    <BookInfo>
      <Title>Eleven Minutes</Title>
      <ISBN>124-445-5466</ISBN>
      <price currency="Dollar">120.0</price>
      <PublicationDate>2011-05-06</PublicationDate>
      <TotalTime>P1Y5M9D</TotalTime>
    </BookInfo>
  </book>
  
<book>
    <author>
      <authorname>
        <lastname>Sheldon</lastname>
        <firstname>Sidney</firstname>
      </authorname>
      <dateofbirth>1974-02-17</dateofbirth>
      <education>MS</education>
      <address>
        <street>276 North Parkway</street>
        <apt>567</apt>
        <city>Chicago</city>
        <zipcode>50154</zipcode>
        <country>USA</country>
      </address>
    </author>
    <PublisherInfo>
      <PublisherName>Williammorrow</PublisherName>
      <PublisherAddress>
        <StreetName>789 Harper Collins</StreetName>
        <City>Newjersey</City>
        <zipcode>45678</zipcode>
        <country>USA</country>
      </PublisherAddress>
    </PublisherInfo>
    <BookInfo>
      <Title>Doomsday Conspiracy</Title>
      <ISBN>123-455-674</ISBN>
      <price currency="Dollar">121.0</price>
      <PublicationDate>1992-03-23</PublicationDate>
      <TotalTime>P2Y5M4D</TotalTime>
    </BookInfo>
  </book>
</Book>
